FROM openjdk:8-jdk-alpine

COPY ./task6/DostavimVse/ /

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

CMD /wait && ./mvnw install -Dstart-class=ru.fivt.dostavimvse.DostavimvseApplication -q -ff -e && java -jar target/dostavimvse-0.0.1-SNAPSHOT.jar
